insert into public.scanned_routes (
  origin_airport,
  destination_airport,
  destination_city,
  bucket,
  teaser,
  trip_nights,
  min_trip_nights,
  max_trip_nights,
  lookahead_start_days,
  lookahead_end_days,
  max_stops
)
values
  ('LUX', 'LHR', 'London', 'weekend_europe', 'Flagship London route with steady city-break and business demand.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'LGW', 'London', 'weekend_europe', 'Alternate London inventory to catch cheaper direct fares.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'STN', 'London', 'weekend_europe', 'Low-cost London inventory that can break below the flagship airports.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'LCY', 'London', 'weekend_europe', 'Premium-facing London option with direct short-haul fare swings.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'CDG', 'Paris', 'weekend_europe', 'Core capital route with stable demand and strong editorial value.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'AMS', 'Amsterdam', 'weekend_europe', 'Short-haul weekend inventory that reacts fast to low-fare releases.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'BER', 'Berlin', 'weekend_europe', 'Popular city-break route that suits long weekends from Luxembourg.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'MUC', 'Munich', 'weekend_europe', 'Frequent direct route with dependable city and event traffic.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'FRA', 'Frankfurt', 'weekend_europe', 'Dense business route that can still produce sharp direct fare drops.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'ZRH', 'Zurich', 'weekend_europe', 'Premium short-haul route with enough variability for deal alerts.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'GVA', 'Geneva', 'weekend_europe', 'Swiss city route with strong business and leisure crossover demand.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'CPH', 'Copenhagen', 'weekend_europe', 'Nordic city break route with clean direct positioning.', 3, 1, 7, 14, 100, 'NON_STOP'),
  ('LUX', 'DUB', 'Dublin', 'weekend_europe', 'Strong leisure route with reliable short-break appeal.', 3, 1, 7, 14, 100, 'NON_STOP'),
  ('LUX', 'VIE', 'Vienna', 'weekend_europe', 'Good for premium weekend inventory and clean nonstop positioning.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'PRG', 'Prague', 'weekend_europe', 'Reliable long-weekend route with broad appeal among Luxembourg subscribers.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'BUD', 'Budapest', 'weekend_europe', 'Price-sensitive weekend traffic makes this route ideal for frequent sends.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'MXP', 'Milan', 'weekend_europe', 'Fashion-week and shoulder-season demand create clean deal narratives.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'LIN', 'Milan', 'weekend_europe', 'Second Milan airport to widen direct fare coverage.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'FCO', 'Rome', 'weekend_europe', 'A dependable editorial route with good click-through when prices dip.', 3, 1, 7, 14, 100, 'NON_STOP'),
  ('LUX', 'BCN', 'Barcelona', 'weekend_europe', 'Classic shoulder-season route with strong open-rate potential.', 4, 1, 7, 21, 120, 'NON_STOP'),
  ('LUX', 'MAD', 'Madrid', 'weekend_europe', 'High-volume city break and gateway route with plenty of fare variance.', 4, 1, 7, 21, 120, 'NON_STOP'),
  ('LUX', 'LIS', 'Lisbon', 'weekend_europe', 'Strong year-round demand and headline-friendly pricing.', 5, 1, 7, 30, 140, 'NON_STOP'),
  ('LUX', 'OPO', 'Porto', 'weekend_europe', 'Lower average fare than Lisbon, useful for consistent deal volume.', 4, 1, 7, 30, 140, 'NON_STOP'),
  ('LUX', 'NCE', 'Nice', 'weekend_europe', 'High-demand Riviera route that suits both city and leisure sends.', 4, 1, 7, 21, 120, 'NON_STOP'),
  ('LUX', 'MRS', 'Marseille', 'weekend_europe', 'Mediterranean city route with direct access to Provence and the coast.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'TLS', 'Toulouse', 'weekend_europe', 'Southern France city route with useful weekend and short-break demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'ATH', 'Athens', 'weekend_europe', 'Mediterranean city-and-sun route with wide fare dispersion.', 5, 1, 7, 30, 150, 'NON_STOP'),
  ('LUX', 'IST', 'Istanbul', 'weekend_europe', 'Longer European-edge city break with strong headline potential.', 5, 1, 7, 30, 150, 'NON_STOP'),
  ('LUX', 'EDI', 'Edinburgh', 'weekend_europe', 'Clean weekend route with reliable seasonal city-break demand.', 3, 1, 7, 14, 100, 'NON_STOP'),
  ('LUX', 'MAN', 'Manchester', 'weekend_europe', 'Useful UK alternative with direct-fare volatility worth tracking.', 3, 1, 7, 14, 100, 'NON_STOP'),
  ('LUX', 'HEL', 'Helsinki', 'weekend_europe', 'Nordic capital route that benefits from planned long-weekend travel.', 4, 1, 7, 21, 120, 'NON_STOP'),
  ('LUX', 'OSL', 'Oslo', 'weekend_europe', 'Nordic route with strong direct-fare visibility.', 4, 1, 7, 21, 120, 'NON_STOP'),
  ('LUX', 'ARN', 'Stockholm', 'weekend_europe', 'Scandinavian city break route with strong appeal for planners.', 4, 1, 7, 21, 120, 'NON_STOP'),
  ('LUX', 'KRK', 'Krakow', 'weekend_europe', 'Classic Eastern Europe city break with good price sensitivity.', 3, 1, 7, 14, 100, 'NON_STOP'),
  ('LUX', 'WAW', 'Warsaw', 'weekend_europe', 'Business-heavy route that still produces useful direct fare dips.', 3, 1, 7, 14, 100, 'NON_STOP'),
  ('LUX', 'LJU', 'Ljubljana', 'weekend_europe', 'Smaller European capital that can stand out in curated sends.', 4, 1, 7, 21, 120, 'NON_STOP'),
  ('LUX', 'OTP', 'Bucharest', 'weekend_europe', 'Eastern Europe capital with strong value perception when prices dip.', 4, 1, 7, 21, 120, 'NON_STOP'),
  ('LUX', 'MLA', 'Malta', 'weekend_europe', 'Island break route with dependable leisure demand and sharp price moves.', 5, 1, 7, 30, 150, 'NON_STOP'),
  ('LUX', 'FAO', 'Faro', 'weekend_europe', 'Classic Algarve route with headline-friendly shoulder-season drops.', 5, 1, 7, 30, 150, 'NON_STOP'),
  ('LUX', 'PMI', 'Palma de Mallorca', 'weekend_europe', 'High-demand island break route with strong deal-email potential.', 5, 1, 7, 30, 150, 'NON_STOP'),
  ('LUX', 'AGP', 'Malaga', 'weekend_europe', 'Southern Spain route that blends city and coastal demand.', 5, 1, 7, 30, 150, 'NON_STOP'),
  ('LUX', 'ALC', 'Alicante', 'weekend_europe', 'Reliable Mediterranean leisure route with frequent direct demand.', 5, 1, 7, 30, 150, 'NON_STOP'),
  ('LUX', 'SVQ', 'Seville', 'weekend_europe', 'Warm-weather city break route with strong spring and autumn appeal.', 4, 1, 7, 21, 130, 'NON_STOP'),
  ('LUX', 'VLC', 'Valencia', 'weekend_europe', 'Coastal city route with useful long-weekend flexibility.', 4, 1, 7, 21, 130, 'NON_STOP'),
  ('LUX', 'IBZ', 'Ibiza', 'weekend_europe', 'Iconic island route that can drive strong seasonal engagement.', 5, 1, 7, 30, 150, 'NON_STOP'),
  ('LUX', 'TFS', 'Tenerife', 'long_haul', 'Canary Islands route with bigger direct price swings across the year.', 6, 1, 7, 35, 170, 'NON_STOP'),
  ('LUX', 'LPA', 'Gran Canaria', 'long_haul', 'Warm-weather leisure route with strong winter newsletter potential.', 6, 1, 7, 35, 170, 'NON_STOP'),
  ('LUX', 'FNC', 'Funchal', 'long_haul', 'Atlantic island route with strong long-weekend and short-holiday appeal.', 6, 1, 7, 35, 170, 'NON_STOP'),
  ('LUX', 'RAK', 'Marrakech', 'weekend_europe', 'North Africa route that routinely creates sharp leisure fare narratives.', 5, 1, 7, 30, 160, 'NON_STOP'),
  ('LUX', 'AGA', 'Agadir', 'weekend_europe', 'Sun-focused route that can anchor beach-heavy sends.', 5, 1, 7, 30, 160, 'NON_STOP'),
  ('LUX', 'HRG', 'Hurghada', 'long_haul', 'Red Sea route with bigger holiday-style fare movements.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'AYT', 'Antalya', 'long_haul', 'High-volume Mediterranean holiday route with broad leisure demand.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'TUN', 'Tunis', 'weekend_europe', 'Useful North Africa capital route with direct leisure appeal.', 5, 1, 7, 30, 160, 'NON_STOP'),
  ('LUX', 'DJE', 'Djerba', 'long_haul', 'Island-style North Africa route with clear package-holiday demand.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'FSC', 'Figari', 'weekend_europe', 'Corsica leisure route with strong summer-season fare swings.', 5, 1, 7, 30, 160, 'NON_STOP'),
  ('LUX', 'CLY', 'Calvi', 'weekend_europe', 'Corsican seasonal route with useful summer deal potential.', 5, 1, 7, 30, 160, 'NON_STOP'),
  ('LUX', 'AJA', 'Ajaccio', 'weekend_europe', 'Corsica capital route with strong summer-only newsletter value.', 5, 1, 7, 30, 160, 'NON_STOP'),
  ('LUX', 'RMI', 'Rimini', 'weekend_europe', 'Italian coast route with seasonal long-weekend utility.', 4, 1, 7, 21, 140, 'NON_STOP'),
  ('LUX', 'PSR', 'Pescara', 'weekend_europe', 'Smaller Italy route that could produce standout niche deals.', 4, 1, 7, 21, 140, 'NON_STOP'),
  ('LUX', 'XRY', 'Jerez de la Frontera', 'weekend_europe', 'Andalusian route with high seasonal leisure interest.', 5, 1, 7, 30, 150, 'NON_STOP'),
  ('LUX', 'ZAD', 'Zadar', 'weekend_europe', 'Croatian coast route with strong summer direct-fare moves.', 5, 1, 7, 30, 160, 'NON_STOP'),
  ('LUX', 'KGS', 'Kos', 'weekend_europe', 'Greek island route with clear package-holiday pricing patterns.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'CFU', 'Corfu', 'weekend_europe', 'Greek island route that works well for summer-leisure alerts.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'CHQ', 'Chania', 'weekend_europe', 'Crete route with broad holiday demand and larger direct swings.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'HER', 'Heraklion', 'weekend_europe', 'Main Crete gateway with strong holiday demand and useful price movement.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'RHO', 'Rhodes', 'weekend_europe', 'Greek island route that can anchor bigger summer drops.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'JFK', 'New York', 'long_haul', 'Flagship long-haul route that justifies premium tiers later.', 7, null, null, 45, 220, 'ONE_STOP_OR_FEWER'),
  ('LUX', 'EWR', 'New York', 'long_haul', 'Alternative New York inventory to avoid single-airport blind spots.', 7, null, null, 45, 220, 'ONE_STOP_OR_FEWER'),
  ('LUX', 'DXB', 'Dubai', 'long_haul', 'Sun-seeking Gulf route with strong promotional copy potential.', 6, null, null, 40, 200, 'ONE_STOP_OR_FEWER'),
  ('LUX', 'AUH', 'Abu Dhabi', 'long_haul', 'Gulf alternative with premium-leaning long-haul demand.', 6, null, null, 40, 200, 'ONE_STOP_OR_FEWER'),
  ('LUX', 'NRT', 'Tokyo', 'long_haul', 'The aspirational route that drives shares even when sends are less frequent.', 8, null, null, 60, 260, 'ONE_STOP_OR_FEWER')
on conflict (origin_airport, destination_airport, max_stops) do update
set
  destination_city = excluded.destination_city,
  teaser = excluded.teaser,
  trip_nights = excluded.trip_nights,
  min_trip_nights = excluded.min_trip_nights,
  max_trip_nights = excluded.max_trip_nights,
  lookahead_start_days = excluded.lookahead_start_days,
  lookahead_end_days = excluded.lookahead_end_days,
  max_stops = excluded.max_stops,
  is_active = true;


-- Direct LUX route catalog synchronization (12 Aug 2026).
insert into public.scanned_routes (
  origin_airport, destination_airport, destination_city, bucket, teaser,
  trip_nights, min_trip_nights, max_trip_nights, lookahead_start_days, lookahead_end_days, max_stops
)
values
  ('LUX', 'HAM', 'Hamburg', 'weekend_europe', 'Direct northern Germany route for city and business travel.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'HDF', 'Heringsdorf', 'weekend_europe', 'Seasonal Baltic coast service from Luxembourg.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'GWT', 'Westerland (Sylt)', 'weekend_europe', 'Seasonal direct access to the island of Sylt.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BOJ', 'Burgas', 'weekend_europe', 'Black Sea holiday route with strong summer demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'VAR', 'Varna', 'weekend_europe', 'Bulgarian coast route with seasonal leisure pricing.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BVC', 'Boa Vista', 'long_haul', 'Cape Verde island route for winter-sun travel.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'RAI', 'Praia', 'long_haul', 'Direct Cape Verde capital service with long-haul leisure demand.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'SID', 'Sal', 'long_haul', 'Cape Verde beach route with winter-sun appeal.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'VXE', 'Sao Vicente', 'long_haul', 'Direct service to Sao Vicente and its Atlantic island market.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'CGO', 'Zhengzhou', 'long_haul', 'Direct China service extending the long-haul discovery catalog.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'BWK', 'Brac', 'weekend_europe', 'Seasonal direct route to the Croatian island of Brac.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'DBV', 'Dubrovnik', 'weekend_europe', 'Popular Adriatic city and coast route.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'RMF', 'Marsa Alam', 'long_haul', 'Red Sea holiday route with seasonal package demand.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'AUH', 'Abu Dhabi', 'long_haul', 'Direct Gulf service with premium and leisure demand.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'DWC', 'Dubai', 'long_haul', 'Direct Dubai World Central service for Gulf travel.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'LEI', 'Almeria', 'weekend_europe', 'Direct Andalusian coast route with seasonal demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BIO', 'Bilbao', 'weekend_europe', 'Northern Spain city route suited to short breaks.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'FUE', 'Fuerteventura', 'long_haul', 'Canary Islands route with strong winter-sun demand.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'GRO', 'Girona', 'weekend_europe', 'Catalonia leisure gateway with low-cost seasonal fares.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'ACE', 'Lanzarote', 'long_haul', 'Lanzarote route with year-round sun demand.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'MAH', 'Menorca', 'weekend_europe', 'Menorca island route with summer leisure demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'SPC', 'La Palma', 'long_haul', 'La Palma route for Canary Islands leisure travel.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'RVN', 'Rovaniemi', 'weekend_europe', 'Seasonal Lapland route with concentrated winter demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BIA', 'Bastia', 'weekend_europe', 'Corsica route serving Bastia and the north of the island.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BIQ', 'Biarritz', 'weekend_europe', 'Atlantic France route for coast and city breaks.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BOD', 'Bordeaux', 'weekend_europe', 'Direct Bordeaux city and wine-region route.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'MPL', 'Montpellier', 'weekend_europe', 'Southern France route with city and coast demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'TLN', 'Toulon', 'weekend_europe', 'Seasonal Riviera route serving Toulon and the Var coast.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'GPA', 'Patras', 'weekend_europe', 'Greek west-coast gateway for Patras and the Peloponnese.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'SKG', 'Thessaloniki', 'weekend_europe', 'Northern Greece city and leisure route.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'ZTH', 'Zakynthos', 'weekend_europe', 'Zakynthos island route with summer holiday demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BRI', 'Bari', 'weekend_europe', 'Puglia gateway with city and coastal demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BLQ', 'Bologna', 'weekend_europe', 'Northern Italy city route with broad short-break appeal.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BZO', 'Bolzano', 'weekend_europe', 'Seasonal Dolomites gateway serving Bolzano.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BDS', 'Brindisi', 'weekend_europe', 'Southern Puglia route with seasonal coast demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'CAG', 'Cagliari', 'weekend_europe', 'Sardinia capital route with strong summer demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'CTA', 'Catania', 'weekend_europe', 'Sicily route serving Catania and the east coast.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'FLR', 'Florence', 'weekend_europe', 'Direct Tuscany city-break route.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'SUF', 'Lamezia Terme', 'weekend_europe', 'Calabria gateway with seasonal leisure demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BGY', 'Milan', 'weekend_europe', 'Low-cost Milan airport adding direct fare coverage.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'NAP', 'Naples', 'weekend_europe', 'Campania gateway with city and coast demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'OLB', 'Olbia', 'weekend_europe', 'Northern Sardinia route with strong summer pricing.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'PMO', 'Palermo', 'weekend_europe', 'Sicily capital route with city and leisure demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'QSR', 'Salerno', 'weekend_europe', 'Salerno and Amalfi Coast gateway.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'VCE', 'Venice', 'weekend_europe', 'Direct Venice route with year-round city-break demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'PXO', 'Porto Santo', 'weekend_europe', 'Seasonal Porto Santo island service.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'TIV', 'Tivat', 'weekend_europe', 'Montenegro coast route with summer leisure demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'DSS', 'Dakar', 'long_haul', 'Direct West Africa service to Dakar.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'NBE', 'Enfidha', 'long_haul', 'Tunisian resort gateway serving Enfidha.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'MIR', 'Monastir', 'long_haul', 'Tunisian coast route serving Monastir.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'ADB', 'Izmir', 'weekend_europe', 'Aegean Turkey route serving Izmir and the coast.', 4, 1, 7, 3, 250, 'NON_STOP')
on conflict (origin_airport, destination_airport, max_stops) do update
set destination_city = excluded.destination_city, teaser = excluded.teaser,
  trip_nights = excluded.trip_nights, min_trip_nights = excluded.min_trip_nights,
  max_trip_nights = excluded.max_trip_nights, lookahead_start_days = excluded.lookahead_start_days,
  lookahead_end_days = excluded.lookahead_end_days, max_stops = excluded.max_stops, is_active = true;

update public.scanned_routes
set buckets = array[bucket]::text[];

update public.scanned_routes
set buckets = array['weekend_europe', 'long_haul']::text[]
where origin_airport = 'LUX'
  and destination_airport in ('IST', 'RAK', 'AGA', 'TUN', 'KGS', 'CFU', 'CHQ', 'HER', 'RHO')
  and max_stops = 'NON_STOP';
