insert into public.scanned_routes (
  origin_airport,
  destination_airport,
  destination_city,
  bucket,
  teaser,
  trip_nights,
  min_trip_nights,
  max_trip_nights,
  lookahead_start_days,
  lookahead_end_days,
  max_stops
)
values
  ('LUX', 'LHR', 'London', 'weekend_europe', 'Flagship London route with steady city-break and business demand.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'LGW', 'London', 'weekend_europe', 'Alternate London inventory to catch cheaper direct fares.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'STN', 'London', 'weekend_europe', 'Low-cost London inventory that can break below the flagship airports.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'LCY', 'London', 'weekend_europe', 'Premium-facing London option with direct short-haul fare swings.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'CDG', 'Paris', 'weekend_europe', 'Core capital route with stable demand and strong editorial value.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'AMS', 'Amsterdam', 'weekend_europe', 'Short-haul weekend inventory that reacts fast to low-fare releases.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'BER', 'Berlin', 'weekend_europe', 'Popular city-break route that suits long weekends from Luxembourg.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'MUC', 'Munich', 'weekend_europe', 'Frequent direct route with dependable city and event traffic.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'FRA', 'Frankfurt', 'weekend_europe', 'Dense business route that can still produce sharp direct fare drops.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'ZRH', 'Zurich', 'weekend_europe', 'Premium short-haul route with enough variability for deal alerts.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'GVA', 'Geneva', 'weekend_europe', 'Swiss city route with strong business and leisure crossover demand.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'CPH', 'Copenhagen', 'weekend_europe', 'Nordic city break route with clean direct positioning.', 3, 1, 7, 14, 100, 'NON_STOP'),
  ('LUX', 'DUB', 'Dublin', 'weekend_europe', 'Strong leisure route with reliable short-break appeal.', 3, 1, 7, 14, 100, 'NON_STOP'),
  ('LUX', 'VIE', 'Vienna', 'weekend_europe', 'Good for premium weekend inventory and clean nonstop positioning.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'PRG', 'Prague', 'weekend_europe', 'Reliable long-weekend route with broad appeal among Luxembourg subscribers.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'BUD', 'Budapest', 'weekend_europe', 'Price-sensitive weekend traffic makes this route ideal for frequent sends.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'MXP', 'Milan', 'weekend_europe', 'Fashion-week and shoulder-season demand create clean deal narratives.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'LIN', 'Milan', 'weekend_europe', 'Second Milan airport to widen direct fare coverage.', 3, 1, 7, 14, 90, 'NON_STOP'),
  ('LUX', 'FCO', 'Rome', 'weekend_europe', 'A dependable editorial route with good click-through when prices dip.', 3, 1, 7, 14, 100, 'NON_STOP'),
  ('LUX', 'BCN', 'Barcelona', 'weekend_europe', 'Classic shoulder-season route with strong open-rate potential.', 4, 1, 7, 21, 120, 'NON_STOP'),
  ('LUX', 'MAD', 'Madrid', 'weekend_europe', 'High-volume city break and gateway route with plenty of fare variance.', 4, 1, 7, 21, 120, 'NON_STOP'),
  ('LUX', 'LIS', 'Lisbon', 'weekend_europe', 'Strong year-round demand and headline-friendly pricing.', 5, 1, 7, 30, 140, 'NON_STOP'),
  ('LUX', 'OPO', 'Porto', 'weekend_europe', 'Lower average fare than Lisbon, useful for consistent deal volume.', 4, 1, 7, 30, 140, 'NON_STOP'),
  ('LUX', 'NCE', 'Nice', 'weekend_europe', 'High-demand Riviera route that suits both city and leisure sends.', 4, 1, 7, 21, 120, 'NON_STOP'),
  ('LUX', 'ATH', 'Athens', 'weekend_europe', 'Mediterranean city-and-sun route with wide fare dispersion.', 5, 1, 7, 30, 150, 'NON_STOP'),
  ('LUX', 'IST', 'Istanbul', 'weekend_europe', 'Longer European-edge city break with strong headline potential.', 5, 1, 7, 30, 150, 'NON_STOP'),
  ('LUX', 'EDI', 'Edinburgh', 'weekend_europe', 'Clean weekend route with reliable seasonal city-break demand.', 3, 1, 7, 14, 100, 'NON_STOP'),
  ('LUX', 'MAN', 'Manchester', 'weekend_europe', 'Useful UK alternative with direct-fare volatility worth tracking.', 3, 1, 7, 14, 100, 'NON_STOP'),
  ('LUX', 'HEL', 'Helsinki', 'weekend_europe', 'Nordic capital route that benefits from planned long-weekend travel.', 4, 1, 7, 21, 120, 'NON_STOP'),
  ('LUX', 'OSL', 'Oslo', 'weekend_europe', 'Nordic route with strong direct-fare visibility.', 4, 1, 7, 21, 120, 'NON_STOP'),
  ('LUX', 'ARN', 'Stockholm', 'weekend_europe', 'Scandinavian city break route with strong appeal for planners.', 4, 1, 7, 21, 120, 'NON_STOP'),
  ('LUX', 'KRK', 'Krakow', 'weekend_europe', 'Classic Eastern Europe city break with good price sensitivity.', 3, 1, 7, 14, 100, 'NON_STOP'),
  ('LUX', 'WAW', 'Warsaw', 'weekend_europe', 'Business-heavy route that still produces useful direct fare dips.', 3, 1, 7, 14, 100, 'NON_STOP'),
  ('LUX', 'LJU', 'Ljubljana', 'weekend_europe', 'Smaller European capital that can stand out in curated sends.', 4, 1, 7, 21, 120, 'NON_STOP'),
  ('LUX', 'OTP', 'Bucharest', 'weekend_europe', 'Eastern Europe capital with strong value perception when prices dip.', 4, 1, 7, 21, 120, 'NON_STOP'),
  ('LUX', 'MLA', 'Malta', 'weekend_europe', 'Island break route with dependable leisure demand and sharp price moves.', 5, 1, 7, 30, 150, 'NON_STOP'),
  ('LUX', 'FAO', 'Faro', 'weekend_europe', 'Classic Algarve route with headline-friendly shoulder-season drops.', 5, 1, 7, 30, 150, 'NON_STOP'),
  ('LUX', 'PMI', 'Palma de Mallorca', 'weekend_europe', 'High-demand island break route with strong deal-email potential.', 5, 1, 7, 30, 150, 'NON_STOP'),
  ('LUX', 'AGP', 'Malaga', 'weekend_europe', 'Southern Spain route that blends city and coastal demand.', 5, 1, 7, 30, 150, 'NON_STOP'),
  ('LUX', 'ALC', 'Alicante', 'weekend_europe', 'Reliable Mediterranean leisure route with frequent direct demand.', 5, 1, 7, 30, 150, 'NON_STOP'),
  ('LUX', 'SVQ', 'Seville', 'weekend_europe', 'Warm-weather city break route with strong spring and autumn appeal.', 4, 1, 7, 21, 130, 'NON_STOP'),
  ('LUX', 'VLC', 'Valencia', 'weekend_europe', 'Coastal city route with useful long-weekend flexibility.', 4, 1, 7, 21, 130, 'NON_STOP'),
  ('LUX', 'IBZ', 'Ibiza', 'weekend_europe', 'Iconic island route that can drive strong seasonal engagement.', 5, 1, 7, 30, 150, 'NON_STOP'),
  ('LUX', 'TFS', 'Tenerife', 'long_haul', 'Canary Islands route with bigger direct price swings across the year.', 6, 1, 7, 35, 170, 'NON_STOP'),
  ('LUX', 'LPA', 'Gran Canaria', 'long_haul', 'Warm-weather leisure route with strong winter newsletter potential.', 6, 1, 7, 35, 170, 'NON_STOP'),
  ('LUX', 'FNC', 'Funchal', 'long_haul', 'Atlantic island route with strong long-weekend and short-holiday appeal.', 6, 1, 7, 35, 170, 'NON_STOP'),
  ('LUX', 'RAK', 'Marrakech', 'weekend_europe', 'North Africa route that routinely creates sharp leisure fare narratives.', 5, 1, 7, 30, 160, 'NON_STOP'),
  ('LUX', 'AGA', 'Agadir', 'weekend_europe', 'Sun-focused route that can anchor beach-heavy sends.', 5, 1, 7, 30, 160, 'NON_STOP'),
  ('LUX', 'HRG', 'Hurghada', 'long_haul', 'Red Sea route with bigger holiday-style fare movements.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'AYT', 'Antalya', 'long_haul', 'High-volume Mediterranean holiday route with broad leisure demand.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'TUN', 'Tunis', 'weekend_europe', 'Useful North Africa capital route with direct leisure appeal.', 5, 1, 7, 30, 160, 'NON_STOP'),
  ('LUX', 'DJE', 'Djerba', 'long_haul', 'Island-style North Africa route with clear package-holiday demand.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'FSC', 'Figari', 'weekend_europe', 'Corsica leisure route with strong summer-season fare swings.', 5, 1, 7, 30, 160, 'NON_STOP'),
  ('LUX', 'CLY', 'Calvi', 'weekend_europe', 'Corsican seasonal route with useful summer deal potential.', 5, 1, 7, 30, 160, 'NON_STOP'),
  ('LUX', 'AJA', 'Ajaccio', 'weekend_europe', 'Corsica capital route with strong summer-only newsletter value.', 5, 1, 7, 30, 160, 'NON_STOP'),
  ('LUX', 'RMI', 'Rimini', 'weekend_europe', 'Italian coast route with seasonal long-weekend utility.', 4, 1, 7, 21, 140, 'NON_STOP'),
  ('LUX', 'PSR', 'Pescara', 'weekend_europe', 'Smaller Italy route that could produce standout niche deals.', 4, 1, 7, 21, 140, 'NON_STOP'),
  ('LUX', 'XRY', 'Jerez de la Frontera', 'weekend_europe', 'Andalusian route with high seasonal leisure interest.', 5, 1, 7, 30, 150, 'NON_STOP'),
  ('LUX', 'ZAD', 'Zadar', 'weekend_europe', 'Croatian coast route with strong summer direct-fare moves.', 5, 1, 7, 30, 160, 'NON_STOP'),
  ('LUX', 'KGS', 'Kos', 'weekend_europe', 'Greek island route with clear package-holiday pricing patterns.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'CFU', 'Corfu', 'weekend_europe', 'Greek island route that works well for summer-leisure alerts.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'CHQ', 'Chania', 'weekend_europe', 'Crete route with broad holiday demand and larger direct swings.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'HER', 'Heraklion', 'weekend_europe', 'Main Crete gateway with strong holiday demand and useful price movement.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'RHO', 'Rhodes', 'weekend_europe', 'Greek island route that can anchor bigger summer drops.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'IST', 'Istanbul', 'long_haul', 'Longer European-edge city break with strong headline potential.', 5, 1, 7, 30, 150, 'NON_STOP'),
  ('LUX', 'RAK', 'Marrakech', 'long_haul', 'North Africa route that routinely creates sharp leisure fare narratives.', 5, 1, 7, 30, 160, 'NON_STOP'),
  ('LUX', 'AGA', 'Agadir', 'long_haul', 'Sun-focused route that can anchor beach-heavy sends.', 5, 1, 7, 30, 160, 'NON_STOP'),
  ('LUX', 'TUN', 'Tunis', 'long_haul', 'Useful North Africa capital route with direct leisure appeal.', 5, 1, 7, 30, 160, 'NON_STOP'),
  ('LUX', 'KGS', 'Kos', 'long_haul', 'Greek island route with clear package-holiday pricing patterns.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'CFU', 'Corfu', 'long_haul', 'Greek island route that works well for summer-leisure alerts.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'CHQ', 'Chania', 'long_haul', 'Crete route with broad holiday demand and larger direct swings.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'HER', 'Heraklion', 'long_haul', 'Main Crete gateway with strong holiday demand and useful price movement.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'RHO', 'Rhodes', 'long_haul', 'Greek island route that can anchor bigger summer drops.', 6, 1, 7, 35, 180, 'NON_STOP'),
  ('LUX', 'JFK', 'New York', 'long_haul', 'Flagship long-haul route that justifies premium tiers later.', 7, null, null, 45, 220, 'ONE_STOP_OR_FEWER'),
  ('LUX', 'EWR', 'New York', 'long_haul', 'Alternative New York inventory to avoid single-airport blind spots.', 7, null, null, 45, 220, 'ONE_STOP_OR_FEWER'),
  ('LUX', 'DXB', 'Dubai', 'long_haul', 'Sun-seeking Gulf route with strong promotional copy potential.', 6, null, null, 40, 200, 'ONE_STOP_OR_FEWER'),
  ('LUX', 'AUH', 'Abu Dhabi', 'long_haul', 'Gulf alternative with premium-leaning long-haul demand.', 6, null, null, 40, 200, 'ONE_STOP_OR_FEWER'),
  ('LUX', 'NRT', 'Tokyo', 'long_haul', 'The aspirational route that drives shares even when sends are less frequent.', 8, null, null, 60, 260, 'ONE_STOP_OR_FEWER')
on conflict (origin_airport, destination_airport, bucket) do update
set
  destination_city = excluded.destination_city,
  teaser = excluded.teaser,
  trip_nights = excluded.trip_nights,
  min_trip_nights = excluded.min_trip_nights,
  max_trip_nights = excluded.max_trip_nights,
  lookahead_start_days = excluded.lookahead_start_days,
  lookahead_end_days = excluded.lookahead_end_days,
  max_stops = excluded.max_stops,
  is_active = true;
