"use client";

import { type PublicDealsSelectOption as SelectOption } from "@/components/public-deals-select";
import {
  type DealSearchSort,
  type DurationFilter,
  type ThemeFilter,
} from "@/lib/public-deals-search";
import {
  type FooterLink,
  type FooterSocial,
  type QuickChip,
} from "@/components/public-deals/types";

export const AIRPORT_TIME_ZONE_BY_CODE: Record<string, string> = {
  AGA: "Africa/Casablanca",
  AGP: "Europe/Madrid",
  AJA: "Europe/Paris",
  ALC: "Europe/Madrid",
  AMS: "Europe/Amsterdam",
  ATH: "Europe/Athens",
  AUH: "Asia/Dubai",
  AYT: "Europe/Istanbul",
  BCN: "Europe/Madrid",
  BER: "Europe/Berlin",
  BUD: "Europe/Budapest",
  CDG: "Europe/Paris",
  CFU: "Europe/Athens",
  CHQ: "Europe/Athens",
  CLY: "Europe/Paris",
  CPH: "Europe/Copenhagen",
  DJE: "Africa/Tunis",
  DUB: "Europe/Dublin",
  DXB: "Asia/Dubai",
  EDI: "Europe/London",
  EWR: "America/New_York",
  FAO: "Europe/Lisbon",
  FCO: "Europe/Rome",
  FNC: "Atlantic/Madeira",
  FRA: "Europe/Berlin",
  FSC: "Europe/Paris",
  GVA: "Europe/Zurich",
  HEL: "Europe/Helsinki",
  HER: "Europe/Athens",
  HRG: "Africa/Cairo",
  IBZ: "Europe/Madrid",
  IST: "Europe/Istanbul",
  JFK: "America/New_York",
  KGS: "Europe/Athens",
  KRK: "Europe/Warsaw",
  LCY: "Europe/London",
  LGW: "Europe/London",
  LHR: "Europe/London",
  LIN: "Europe/Rome",
  LIS: "Europe/Lisbon",
  LJU: "Europe/Ljubljana",
  LPA: "Atlantic/Canary",
  LUX: "Europe/Luxembourg",
  MAD: "Europe/Madrid",
  MAN: "Europe/London",
  MLA: "Europe/Malta",
  MUC: "Europe/Berlin",
  MXP: "Europe/Rome",
  NCE: "Europe/Paris",
  NRT: "Asia/Tokyo",
  OPO: "Europe/Lisbon",
  OSL: "Europe/Oslo",
  OTP: "Europe/Bucharest",
  PMI: "Europe/Madrid",
  PRG: "Europe/Prague",
  PSR: "Europe/Rome",
  RAK: "Africa/Casablanca",
  RHO: "Europe/Athens",
  RMI: "Europe/Rome",
  ARN: "Europe/Stockholm",
  STN: "Europe/London",
  SVQ: "Europe/Madrid",
  TFS: "Atlantic/Canary",
  TUN: "Africa/Tunis",
  VLC: "Europe/Madrid",
  VIE: "Europe/Vienna",
  WAW: "Europe/Warsaw",
  XRY: "Europe/Madrid",
  ZAD: "Europe/Zagreb",
  ZRH: "Europe/Zurich",
};

export const LANDMARK_TITLE_BY_DESTINATION: Record<string, string> = {
  agadir: "Kasbah of Agadir Oufella",
  ajaccio: "Citadel of Ajaccio",
  antalya: "Hadrian's Gate",
  "abu dhabi": "Sheikh Zayed Grand Mosque",
  barcelona: "Sagrada Familia",
  berlin: "Brandenburg Gate",
  bordeaux: "Place de la Bourse",
  cagliari: "Saint Remy's Bastion",
  corfu: "Old Fortress, Corfu",
  copenhagen: "The Little Mermaid",
  djerba: "El Ghriba Synagogue",
  dublin: "Ha'penny Bridge",
  dubai: "Dubai Fountain",
  edinburgh: "Edinburgh Castle",
  faro: "Arco da Vila",
  florence: "Ponte Vecchio",
  heraklion: "Knossos",
  hurghada: "El Mina Mosque",
  istanbul: "Hagia Sophia",
  "jerez de la frontera": "Alcazar of Jerez de la Frontera",
  kos: "Neratzia Castle",
  lisbon: "Belem Tower",
  london: "Big Ben",
  madrid: "Puerta de Alcala",
  malaga: "Alcazaba of Malaga",
  malta: "St. John's Co-Cathedral",
  marrakech: "Koutoubia Mosque",
  milan: "Milan Cathedral",
  munich: "Marienplatz",
  mykonos: "Windmills of Mykonos",
  nice: "Place Massena",
  "new york": "Brooklyn Bridge",
  palma: "Palma Cathedral",
  paris: "Pont Alexandre III",
  porto: "Dom Luis I Bridge",
  rimini: "Arch of Augustus",
  rome: "Colosseum",
  stockholm: "Stockholm City Hall",
  stuttgart: "Schlossplatz",
  tunis: "Al-Zaytuna Mosque",
  valencia: "City of Arts and Sciences",
  vienna: "Schonbrunn Palace",
  warsaw: "Royal Castle, Warsaw",
  zurich: "Quaibrucke, Zurich",
  zadar: "Sea Organ",
};

export const WHEN_OPTIONS: SelectOption[] = [
  { value: "any", label: "Anytime" },
  { value: "this_weekend", label: "This weekend" },
  { value: "weekends", label: "Weekends" },
  { value: "next_30", label: "Next 30 days" },
  { value: "this_month", label: "This month" },
  { value: "next_month", label: "Next month" },
  { value: "this_year", label: "This year" },
  { value: "next_year", label: "Next year" },
  { value: "school_holidays", label: "School holidays" },
];

export const TRIP_OPTIONS: SelectOption[] = [
  { value: "any", label: "Any trip" },
  { value: "weekend", label: "Weekend" },
  { value: "weeklong", label: "5 to 7 nights" },
  { value: "long_stay", label: "Long stay" },
];

export const DEPARTURE_WEEKDAY_OPTIONS: SelectOption[] = [
  { value: "any", label: "Any day" },
  { value: "monday", label: "Monday" },
  { value: "tuesday", label: "Tuesday" },
  { value: "wednesday", label: "Wednesday" },
  { value: "thursday", label: "Thursday" },
  { value: "friday", label: "Friday" },
  { value: "saturday", label: "Saturday" },
  { value: "sunday", label: "Sunday" },
];

export const DURATION_FILTER_VALUES: Exclude<DurationFilter, "any">[] = [
  "2",
  "3",
  "4",
  "5",
  "6_plus",
];

export const DEAL_SORT_OPTIONS: SelectOption[] = [
  { value: "best", label: "Best deals" },
  { value: "price_asc", label: "Price: lowest first" },
  { value: "price_desc", label: "Price: highest first" },
  { value: "departure_soonest", label: "Departure: soonest first" },
  { value: "departure_latest", label: "Departure: latest first" },
  { value: "trip_shortest", label: "Trip length: shortest first" },
  { value: "trip_longest", label: "Trip length: longest first" },
];

export const DEAL_SORT_TRANSLATION_KEYS: Record<DealSearchSort, string> = {
  best: "deals.sort.best",
  price_asc: "deals.sort.priceAsc",
  price_desc: "deals.sort.priceDesc",
  departure_soonest: "deals.sort.departureSoonest",
  departure_latest: "deals.sort.departureLatest",
  trip_shortest: "deals.sort.tripShortest",
  trip_longest: "deals.sort.tripLongest",
};

export const QUICK_CHIP_OPTIONS: QuickChip[] = [
  "weekend",
  "this_weekend",
  "weeklong",
  "school_holidays",
  "under_50",
  "cheap_direct",
  "direct",
  "beach",
  "city",
  "nature",
];

export const SEARCH_QUICK_CHIPS: QuickChip[] = [
  "this_weekend",
  "weeklong",
  "school_holidays",
  "under_50",
  "direct",
  "beach",
  "city",
  "nature",
];

export const RESULTS_PAGE_SIZE_OPTIONS = [10, 20, 50, 100, 200] as const;

export const DEFAULT_RESULTS_PAGE_SIZE = RESULTS_PAGE_SIZE_OPTIONS[0];

export const STRONG_PRICE_VISUAL_RATIO = 0.8;

export const THEME_BY_DESTINATION: Record<string, ThemeFilter> = {
  agadir: "beach",
  ajaccio: "beach",
  antalya: "beach",
  "abu dhabi": "city",
  barcelona: "city",
  berlin: "city",
  bordeaux: "city",
  cagliari: "beach",
  corfu: "beach",
  copenhagen: "city",
  djerba: "beach",
  dublin: "city",
  dubai: "city",
  edinburgh: "city",
  florence: "city",
  heraklion: "beach",
  hurghada: "beach",
  istanbul: "city",
  "jerez de la frontera": "city",
  kos: "beach",
  lisbon: "city",
  london: "city",
  madrid: "city",
  malaga: "beach",
  marrakech: "city",
  milan: "city",
  munich: "city",
  mykonos: "beach",
  nice: "beach",
  "new york": "city",
  palma: "beach",
  paris: "city",
  porto: "city",
  rimini: "beach",
  rome: "city",
  stockholm: "city",
  stuttgart: "city",
  tunis: "city",
  valencia: "beach",
  vienna: "city",
  warsaw: "city",
  zurich: "nature",
  zadar: "nature",
};

export const DESTINATION_ESCAPE_LABEL_BY_DESTINATION: Record<string, string> = {
  milan: "Italian escape",
  florence: "Tuscan escape",
  rome: "Italian city break",
  barcelona: "Spanish city break",
  madrid: "Spanish escape",
  malaga: "Costa del Sol break",
  valencia: "Mediterranean city break",
  lisbon: "Portuguese escape",
  porto: "Portuguese city break",
  paris: "Paris escape",
  london: "London break",
  dublin: "Irish break",
  edinburgh: "Scottish escape",
  berlin: "German city break",
  munich: "Bavarian escape",
  vienna: "Austrian city break",
  stockholm: "Scandinavian escape",
  copenhagen: "Nordic city break",
  zurich: "Swiss escape",
  warsaw: "Polish city break",
  nice: "French Riviera escape",
  marrakech: "Moroccan escape",
  dubai: "Gulf escape",
  "new york": "New York getaway",
  palma: "Mallorca escape",
  mykonos: "Greek island escape",
  corfu: "Greek island break",
  cagliari: "Sardinian escape",
  kos: "Greek beach break",
  heraklion: "Cretan escape",
  antalya: "Turkish Riviera escape",
  agadir: "Atlantic coast escape",
  ajaccio: "Corsican escape",
  djerba: "island break",
  hurghada: "Red Sea escape",
  zadar: "Croatian coast break",
  rimini: "Italian seaside break",
  tunis: "North African city break",
  bordeaux: "French city break",
  istanbul: "cross-continental escape",
  "abu dhabi": "desert city break",
};

export const DEALS_FOOTER_LINKS: FooterLink[] = [
  { href: "/privacy", label: "Privacy policy" },
  { href: "/cookies", label: "Cookies" },
  { href: "/terms", label: "Terms" },
];

export const DEALS_FOOTER_SOCIALS: FooterSocial[] = [
  { label: "Instagram", icon: "◎" },
  { label: "TikTok", icon: "♪" },
  { label: "LinkedIn", icon: "in" },
];

export const HERO_REFERENCE_CARDS = [
  {
    city: "Rome",
    price: "€68",
    landmarkTitle: "Colosseum",
  },
  {
    city: "Lisbon",
    price: "€55",
    landmarkTitle: "Belem Tower",
  },
  {
    city: "Budapest",
    price: "€39",
    landmarkTitle: "Hungarian Parliament Building",
  },
] as const;

export const AIRLINE_LOGO_CODE_BY_NAME: Record<string, string> = {
  aegean: "A3",
  "aegean airlines": "A3",
  "air europa": "UX",
  "air france": "AF",
  "air malta": "KM",
  "air serbia": "JU",
  "air corsica": "XK",
  "air dolomiti": "EN",
  airbaltic: "BT",
  "american airlines": "AA",
  austrian: "OS",
  "austrian airlines": "OS",
  "british airways": "BA",
  "brussels airlines": "SN",
  "croatia airlines": "OU",
  condor: "DE",
  "delta air lines": "DL",
  easyjet: "U2",
  emirates: "EK",
  etihad: "EY",
  "etihad airways": "EY",
  eurowings: "EW",
  finnair: "AY",
  iberia: "IB",
  "ita airways": "AZ",
  klm: "KL",
  lot: "LO",
  "lot polish airlines": "LO",
  lufthansa: "LH",
  luxair: "LG",
  norwegian: "DY",
  "norwegian air shuttle": "DY",
  pegasus: "PC",
  "pegasus airlines": "PC",
  "qatar airways": "QR",
  "royal air maroc": "AT",
  ryanair: "FR",
  sas: "SK",
  "scandinavian airlines": "SK",
  swiss: "LX",
  "swiss international air lines": "LX",
  tap: "TP",
  "tap air portugal": "TP",
  "tap portugal": "TP",
  transavia: "HV",
  "transavia airlines": "HV",
  "tui fly": "TB",
  "tui fly belgium": "TB",
  "turkish airlines": "TK",
  "united airlines": "UA",
  volotea: "V7",
  vueling: "VY",
  "wizz air": "W6",
};

export const BEST_DEAL_PREFERRED_STAY_HOURS = 48;

export const BEST_DEAL_FRESHNESS_WINDOW_MS = 7 * 24 * 60 * 60 * 1000;
