insert into public.scanned_routes (
  origin_airport, destination_airport, destination_city, bucket, teaser,
  trip_nights, min_trip_nights, max_trip_nights, lookahead_start_days, lookahead_end_days, max_stops
)
values
  ('LUX', 'HAM', 'Hamburg', 'weekend_europe', 'Direct northern Germany route for city and business travel.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'HDF', 'Heringsdorf', 'weekend_europe', 'Seasonal Baltic coast service from Luxembourg.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'GWT', 'Westerland (Sylt)', 'weekend_europe', 'Seasonal direct access to the island of Sylt.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BOJ', 'Burgas', 'weekend_europe', 'Black Sea holiday route with strong summer demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'VAR', 'Varna', 'weekend_europe', 'Bulgarian coast route with seasonal leisure pricing.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BVC', 'Boa Vista', 'long_haul', 'Cape Verde island route for winter-sun travel.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'RAI', 'Praia', 'long_haul', 'Direct Cape Verde capital service with long-haul leisure demand.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'SID', 'Sal', 'long_haul', 'Cape Verde beach route with winter-sun appeal.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'VXE', 'Sao Vicente', 'long_haul', 'Direct service to Sao Vicente and its Atlantic island market.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'CGO', 'Zhengzhou', 'long_haul', 'Direct China service extending the long-haul discovery catalog.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'BWK', 'Brac', 'weekend_europe', 'Seasonal direct route to the Croatian island of Brac.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'DBV', 'Dubrovnik', 'weekend_europe', 'Popular Adriatic city and coast route.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'RMF', 'Marsa Alam', 'long_haul', 'Red Sea holiday route with seasonal package demand.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'AUH', 'Abu Dhabi', 'long_haul', 'Direct Gulf service with premium and leisure demand.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'DWC', 'Dubai', 'long_haul', 'Direct Dubai World Central service for Gulf travel.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'LEI', 'Almeria', 'weekend_europe', 'Direct Andalusian coast route with seasonal demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BIO', 'Bilbao', 'weekend_europe', 'Northern Spain city route suited to short breaks.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'FUE', 'Fuerteventura', 'long_haul', 'Canary Islands route with strong winter-sun demand.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'GRO', 'Girona', 'weekend_europe', 'Catalonia leisure gateway with low-cost seasonal fares.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'ACE', 'Lanzarote', 'long_haul', 'Lanzarote route with year-round sun demand.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'MAH', 'Menorca', 'weekend_europe', 'Menorca island route with summer leisure demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'SPC', 'La Palma', 'long_haul', 'La Palma route for Canary Islands leisure travel.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'RVN', 'Rovaniemi', 'weekend_europe', 'Seasonal Lapland route with concentrated winter demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BIA', 'Bastia', 'weekend_europe', 'Corsica route serving Bastia and the north of the island.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BIQ', 'Biarritz', 'weekend_europe', 'Atlantic France route for coast and city breaks.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BOD', 'Bordeaux', 'weekend_europe', 'Direct Bordeaux city and wine-region route.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'MPL', 'Montpellier', 'weekend_europe', 'Southern France route with city and coast demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'TLN', 'Toulon', 'weekend_europe', 'Seasonal Riviera route serving Toulon and the Var coast.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'GPA', 'Patras', 'weekend_europe', 'Greek west-coast gateway for Patras and the Peloponnese.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'SKG', 'Thessaloniki', 'weekend_europe', 'Northern Greece city and leisure route.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'ZTH', 'Zakynthos', 'weekend_europe', 'Zakynthos island route with summer holiday demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BRI', 'Bari', 'weekend_europe', 'Puglia gateway with city and coastal demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BLQ', 'Bologna', 'weekend_europe', 'Northern Italy city route with broad short-break appeal.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BZO', 'Bolzano', 'weekend_europe', 'Seasonal Dolomites gateway serving Bolzano.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BDS', 'Brindisi', 'weekend_europe', 'Southern Puglia route with seasonal coast demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'CAG', 'Cagliari', 'weekend_europe', 'Sardinia capital route with strong summer demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'CTA', 'Catania', 'weekend_europe', 'Sicily route serving Catania and the east coast.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'FLR', 'Florence', 'weekend_europe', 'Direct Tuscany city-break route.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'SUF', 'Lamezia Terme', 'weekend_europe', 'Calabria gateway with seasonal leisure demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'BGY', 'Milan', 'weekend_europe', 'Low-cost Milan airport adding direct fare coverage.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'NAP', 'Naples', 'weekend_europe', 'Campania gateway with city and coast demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'OLB', 'Olbia', 'weekend_europe', 'Northern Sardinia route with strong summer pricing.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'PMO', 'Palermo', 'weekend_europe', 'Sicily capital route with city and leisure demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'QSR', 'Salerno', 'weekend_europe', 'Salerno and Amalfi Coast gateway.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'VCE', 'Venice', 'weekend_europe', 'Direct Venice route with year-round city-break demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'PXO', 'Porto Santo', 'weekend_europe', 'Seasonal Porto Santo island service.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'TIV', 'Tivat', 'weekend_europe', 'Montenegro coast route with summer leisure demand.', 4, 1, 7, 3, 250, 'NON_STOP'),
  ('LUX', 'DSS', 'Dakar', 'long_haul', 'Direct West Africa service to Dakar.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'NBE', 'Enfidha', 'long_haul', 'Tunisian resort gateway serving Enfidha.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'MIR', 'Monastir', 'long_haul', 'Tunisian coast route serving Monastir.', 7, 1, 14, 3, 250, 'NON_STOP'),
  ('LUX', 'ADB', 'Izmir', 'weekend_europe', 'Aegean Turkey route serving Izmir and the coast.', 4, 1, 7, 3, 250, 'NON_STOP')
on conflict (origin_airport, destination_airport, bucket) do update
set destination_city = excluded.destination_city, teaser = excluded.teaser,
  trip_nights = excluded.trip_nights, min_trip_nights = excluded.min_trip_nights,
  max_trip_nights = excluded.max_trip_nights, lookahead_start_days = excluded.lookahead_start_days,
  lookahead_end_days = excluded.lookahead_end_days, max_stops = excluded.max_stops, is_active = true;
